export const Colors = {
  primary: '#0D4F3C',
  primaryLight: '#1A6B54',
  primaryDark: '#082E23',
  accent: '#25D366',
  accentLight: '#DCF8C6',
  background: '#FFFFFF',
  backgroundSecondary: '#F5F5F5',
  backgroundTertiary: '#EBEBEB',
  bubbleUser: '#DCF8C6',
  bubbleAgent: '#FFFFFF',
  bubbleAgentBorder: '#E8E8E8',
  textPrimary: '#1A1A1A',
  textSecondary: '#8A8A8A',
  textTertiary: '#BBBBBB',
  textOnPrimary: '#FFFFFF',
  border: '#E8E8E8',
  borderLight: '#F0F0F0',
  inputBackground: '#F5F5F5',
  separator: '#EEEEEE',
  online: '#4CAF50',
  offline: '#BBBBBB',
  error: '#E53935',
  tabActive: '#0D4F3C',
  tabInactive: '#9E9E9E',
  overlay: 'rgba(0,0,0,0.5)',
};
